# Main composition file for SIG Application Container.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore
# Capacitação Redes - PV Intelbras

version: '3.8'
services:
  # Application container
  ansibleserver:
    container_name: ansibleserver
    ports:
      - "2000:22" # SSH access port
    # Mount local directories as volumes inside the container:
    volumes:
      - "./inventory/:/ansible/inventory"
      - "./playbooks/:/ansible/playbooks"
      - "./config/ansible.cfg:/usr/lib/python3.8/site-packages/ansible/galaxy/data/apb/tests/ansible.cfg"
    build:
      context: .
      dockerfile: ./app/Dockerfile
