# Main composition file for Ansbile Application Container.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore
# Capacitação Redes - PV Intelbras

version: '3.8'
services:
  # Application container
  ansibleserver:
    container_name: ansibleserver
    volumes:
      - "./inventory/:/ansible/inventory/"
      - "./playbooks/playbooks.sh:/ansible/playbooks.sh"
      - "./playbooks/switch.yaml:/ansible/switch.yaml"
      - "./config/hosts:/etc/hosts"
      - "./libs/:/ansible/"
      - ./env/namespaces.py:/usr/local/lib/python3.10/dist-packages/pycw7-0.0.11-py3.10.egg/pycw7/utils/xml/namespaces.py
      - ./env/namespaces.py:/ansible/pycw7/utils/xml/namespaces.py
    #  - ./env/namespaces.py:/ansible/build/lib/pycw7/utils/xml/namespaces.py
    build:
      context: .
      dockerfile: ./docker/Dockerfile
