all:
  children:
    web:
      hosts:
        apache:
          ansible_host: 10.1.40.205
          ansible_user: capacita
          ansible_ssh_pass: "{{ lookup('env', 'HOST_PASSWORD_APACHE') }}"
        nginx:
          ansible_host: 10.1.40.206
          ansible_user: capacita2
          ansible_ssh_pass: "{{ lookup('env', 'HOST_PASSWORD_NGINX') }}"
        daloradius:
          ansible_host: 10.1.40.207
          ansible_user: capacita3
          ansible_ssh_pass: "{{ lookup('env', 'HOST_PASSWORD_DALORADIUS') }}"
    database:
      hosts:
        db_server:
          ansible_host: 10.1.40.200
          ansible_user: capacitadb1
          ansible_ssh_pass: "{{ lookup('env', 'HOST_PASSWORD_DB_SERVER') }}"
        db_server2:
          ansible_host: 10.1.40.201
          ansible_user: capacitadb2
          ansible_ssh_pass: "{{ lookup('env', 'HOST_PASSWORD_DB_SERVER2') }}"
