# Dockerfile: Defines container specifications to startup and run.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore
# Capacitação Redes - PV Intelbras

FROM alpinelinux/ansible:latest-x86_64

CMD ["tail", "-f", "/dev/null"]

