---
- name: Install Apache and net-tools on Ubuntu 22.04
  hosts: web  # Replace 'your_host' with the host or group from your inventory file
  become: yes  # Run tasks with root privileges
  become_user: root # Specify the user for privilege escalation
  become_method: sudo # Specify the method for privilege escalation
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Install net-tools package
      apt:
        name: net-tools
        state: present

    - name: Ensure Apache service is enabled and running
      systemd:
        name: apache2
        enabled: yes
        state: started