---
- name: Install Apache and net-tools on Ubuntu 22.04
  hosts: web  
  become: yes  
  become_user: root 
  become_method: sudo
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Install net-tools package
      apt:
        name: net-tools
        state: present

    - name: Ensure Apache service is enabled and running
      systemd:
        name: apache2
        enabled: yes
        state: started