---
- name: Configure VLANs and interfaces on Intelbras Switch
  hosts: switches
  gather_facts: no
  connection: network_cli

  tasks:
    - name: ensure VLAN 10 exists
      comware_vlan: vlanid=10 name=VLAN10 descr=LOCAL_SEGMENT username={{ username }} password={{ password }} hostname={{ inventory_hostname }}

    - name: ensure VLAN 20 exists
      comware_vlan: vlanid=20 state=present username={{ username }} password={{ password }} hostname={{ inventory_hostname }}


