---
- name: Uptime discovery playbook
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Get uptime
      comware_command:
        command:
          - display version | include uptime
        type: display
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
