---
- name: Net-tools, and Zabbix Agent on Ubuntu 22.04
  hosts: web  
  become: yes  
  become_user: root 
  become_method: sudo
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install net-tools package
      apt:
        name: net-tools
        state: present

    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    - name: Ensure Zabbix Agent service is enabled and running
      systemd:
        name: zabbix-agent
        enabled: yes
        state: started
